### ISSUE TITLE
Error: EEXIST: file already exists, symlink MANIFEST.Redist

### ISSUE THREAD

**Issue by adamdecaf** [SeyfSV/setup-mqclient#5]
I was trying out v0.1.4 and v0.2.0 in my project, but was seeing multiple failures when the job runs on a runner where a previous run took place. 

```
Downloading MQ Client...
Downloaded
Extracting archive "/home/actions/actions-runner/_work/rtp-certification-testing/rtp-certification-testing/distr/[9](https://github.com/moovfinancial/rtp-certification-testing/actions/runs/3175528958/jobs/5173680777#step:3:10).3.0.0-IBM-MQC-Redist-LinuxX64.tar.gz" to "/home/actions/IBM/MQ/data" ...

Error: EEXIST: file already exists, symlink 'MANIFEST.Redist' -> '/home/actions/IBM/MQ/data/MANIFEST'
```

**Comment by adamdecaf** [comment]
I'm not very familiar with node.js, but I opened https://github.com/SeyfSV/setup-mqclient/pull/6 which should work around this. We can delete the old output dir prior to extracting the latest package.

**Comment by SeyfSV** [comment]
Hi @adamdecaf !
Thank you for the issue and PR.
I will see by the end of the week. But I think that overwrite should be optional and/or different paths should be used for each MQ version. 
Could you describe your case?
Wouldn't it be better to put MQ to the WORKDIR and then cleanup everything related to the particular build.

**Comment by adamdecaf** [comment]
> Wouldn't it be better to put MQ to the WORKDIR and then cleanup everything related to the particular build.

Yes this would make sense to me. We're looking at using the IBM messaging libraries which ask for everything to be installed in a specific place, but as long as it's on `PATH` I think it'll be fine.

https://github.com/ibm-messaging/mq-golang#linux
https://github.com/ibm-messaging/mq-golang-jms20

The error about files existing was happening without additional changes, so I figured it was a bug with this Action.

**Comment by SeyfSV** [comment]
New version v0.3.0 released
